# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCNY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=99, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_cny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=99, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_usd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('bank_acct', models.CharField(blank=True, max_length=99, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=99, null=True)),
                ('txn_category', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.CharField(blank=True, max_length=99, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('bank_acct', models.CharField(blank=True, max_length=99, null=True)),
                ('gross_income', models.FloatField(blank=True, null=True)),
                ('tax_paid', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.CharField(blank=True, max_length=99, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentCNY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=99, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investment_cny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('bank_acct', models.CharField(blank=True, max_length=99, null=True)),
                ('inv_acct', models.CharField(blank=True, max_length=99, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.CharField(blank=True, max_length=99, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investment_transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=99, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investment_usd',
                'managed': False,
            },
        ),
    ]
